# Generated by Django 2.1 on 2018-08-12 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sober_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='cached_avg_vote',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='brick',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='brick',
            name='creation_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bricks', to='sober_app.User'),
        ),
        migrations.AddField(
            model_name='brick',
            name='references',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='brick',
            name='update_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brick',
            name='tags',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
