# Generated by Django 2.1 on 2018-09-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sober_app', '0003_remove_brick_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsBunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=10)),
                ('max_rlevel', models.SmallIntegerField(default=8)),
            ],
        ),
        migrations.AlterField(
            model_name='brick',
            name='references',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='brick',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Thesis'), (2, 'Pro'), (3, 'Contra'), (4, 'Comment'), (5, 'Question'), (6, 'Improvement')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sober_app.SettingsBunch'),
        ),
    ]
