# Generated by Django 2.1.1 on 2018-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sober', '0004_auto_20180907_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsbunch',
            name='max_rlevel',
            field=models.SmallIntegerField(default=8, verbose_name='Maximum relative level to display'),
        ),
    ]
