# Generated by Django 2.1 on 2018-08-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sober_app', '0002_auto_20180812_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brick',
            name='datetime',
        ),
    ]
